config/routes.rb
Rails.application.routes.draw do
  resources :awards
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users do
  resources :cars
  end
  resources :cars

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
class Award < ApplicationRecord
  belongs_to :car
  has_one :user, through: :cars
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :awards
  belongs_to :user
  validates_presence_of :make, :model, :year, :color
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  extend Devise::Models
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :cars
  has_many :awards, through: :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  before_action :set_award, only: [:show, :create]

  def new
    @award = Award.new
  end

  def index
    @awards = Award.all
  end

  def create
    if @award.valid?
      @award.save
      redirect_to award_path(@award)
    else
      render :new
    end
  end

  def show
  end

  def destroy
  end

  private

  def set_award
    @award = Award.find(params[:id])
  end

  def award_params
    params.require[:award].permit(:make,:model,:year,:color)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  def new
    @car = Car.new
  end

  def index
    @cars = Car.all
  end

  def create
    @car = Car.new(car_params)
    @car.save
    current_user.cars << @car
    redirect_to current_user, :flash => { :success => "car created!" }
  end

  def edit
  end

  def update
    @car.update(car_params)
    if @car.valid?
      @car.save
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def show
    @car = Car.find(params[:id])
  end

  def destroy
    @car.destroy
    redirect_to user_path(current_user)
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:make,:model,:year,:color)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:user_id])
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @user = User.find_by(id: params[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/awards/new.html.erb
<h1>Add An Award:</h1>

app/views/awards/show.html.erb
<h1><%= @award %></h1>

app/views/cars/_form.html.erb
<%= form_for @car do |f| %>

  <%= f.label :make %>
  <%= f.text_field :make %><br>

  <%= f.label :model %>
  <%= f.text_field :model %><br>

  <%= f.label :color %>
  <%= f.text_field :color %><br>

  <%= f.label :year %>
  <%= f.text_field :year %><br>

  <%= f.submit %>

<%end%>

app/views/cars/edit.html.erb
<h1> Edit <%= @car.make %> <%= @car.model %></h1>

<%= render 'form' %>

app/views/cars/index.html.erb
<%= render 'layouts/header' %>
<h1> All Cars: </h1>

<% @cars.each do |car| %>
  <h2> <%= link_to "#{@car.make} #{@car.model}", car_path(@car) %></h2>
  <h2> <%= @car.year%></h2>
  <h2> <%= @car.color %></h2>
  <h2> <%= @car.user.email %></h2>
  <br><br>
<% end %>

app/views/cars/new.html.erb
<%= render 'layouts/header' %>
<h1>Add a New Car:</h1>
<%= render 'form' %>

app/views/cars/show.html.erb
<h1><%= "#{@car.make} #{@car.model}" %></h1>

app/views/layouts/_header.html.erb
<h1>Classic Car Collections</h1>

<button class="btn btn-default"><%= link_to "Home", root_path %></button>

<% if user_signed_in? %>
  <button class="btn btn-default"><%= link_to "My cars", user_path(current_user) %></button>
  <button class="btn btn-default"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></button><br><br>
  <%= "Signed in as #{current_user.email}" %><br>
<% else %>
  <button class="btn btn-default"><%= link_to "Sign Up", new_user_registration_path %></button>
  <button class="btn btn-default"><%= link_to "Sign In", new_user_session_path %></button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Classic Car Collections</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>All Users:</h1>

<% @users.each do |user| %>
<h2> <%= link_to @user.name, user_path(@user) %></h2>
<h2> <%= @user.hometown %></h2>
<br><br>
<% end %>

app/views/users/show.html.erb
<%= render 'layouts/header' %>
<h1>Your Cars</h1>

<ul>
  <% if user_signed_in? %>
    <% current_user.cars.each do |car| %>
      <li><%= car.color %></li>
      <li><%= car.make %></li>
      <li><%= car.model %></li>
      <li><%= car.year %></li>
      <button class="btn btn-default"><%= link_to 'Edit', edit_car_path(car) %></button>
      <button class="btn btn-default"><%= link_to 'Delete', car,  :data => {:confirm => "You Sure?", :method => :delete}  %></button>
    <%end%>
  <%end%>
</ul>

<% if user_signed_in? %>
  <button class="btn btn-default"><%=link_to "Add a car", new_user_car_path(current_user)%></button>
<%end%>

app/views/welcome/home.html.erb
<%= render 'layouts/header' %>
<%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>